import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Agent } from './entities/agent.entity';

export interface AgentManifest {
  id: string;
  name: string;
  role: string;
  domain: string;
  team: 'coding' | 'general' | 'research' | 'custom';
  domainKeywords: string[];
  safePair: string | null;
  mcpTools: string[];
  costTier: 'low' | 'medium' | 'high';
  isCustom: boolean;
  tenantId: string | null;
}

const PLATFORM_SPECIALISTS: AgentManifest[] = [
  // CODING TEAM
  {
    id: 'rex',
    name: 'Rex',
    role: 'specialist',
    domain: 'backend',
    team: 'coding',
    domainKeywords: [
      'backend',
      'api',
      'database',
      'sql',
      'migration',
      'endpoint',
      'server',
      'nestjs',
      'typeorm',
    ],
    safePair: 'kai',
    mcpTools: ['postgresql', 'context7', 'github', 'filesystem', 'digma'],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'specialist',
    domain: 'frontend',
    team: 'coding',
    domainKeywords: [
      'frontend',
      'ui',
      'component',
      'css',
      'react',
      'nextjs',
      'page',
      'style',
      'accessibility',
    ],
    safePair: 'kai',
    mcpTools: ['playwright', 'figma', 'context7', 'github', 'filesystem'],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'kai',
    name: 'Kai',
    role: 'specialist',
    domain: 'review',
    team: 'coding',
    domainKeywords: [
      'review',
      'audit',
      'check',
      'lint',
      'approve',
      'code review',
    ],
    safePair: null,
    mcpTools: ['context7', 'github', 'filesystem'],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'sage',
    name: 'Sage',
    role: 'specialist',
    domain: 'testing',
    team: 'coding',
    domainKeywords: [
      'test',
      'spec',
      'coverage',
      'e2e',
      'playwright',
      'jest',
      'unit test',
    ],
    safePair: 'pixel',
    mcpTools: ['playwright', 'context7', 'github', 'filesystem'],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'specialist',
    domain: 'devops',
    team: 'coding',
    domainKeywords: [
      'deploy',
      'docker',
      'ci',
      'server',
      'infra',
      'kubernetes',
      'pipeline',
      'devops',
    ],
    safePair: null,
    mcpTools: ['kubernetes', 'digitalocean', 'heroku', 'github', 'filesystem'],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'orion',
    name: 'Orion',
    role: 'specialist',
    domain: 'architecture',
    team: 'coding',
    domainKeywords: [
      'architecture',
      'design',
      'plan',
      'structure',
      'diagram',
      'architect',
    ],
    safePair: null,
    mcpTools: ['context7', 'github', 'filesystem'],
    costTier: 'high',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'pixel',
    name: 'Pixel',
    role: 'specialist',
    domain: 'debugging',
    team: 'coding',
    domainKeywords: [
      'bug',
      'error',
      'crash',
      'fix',
      'debug',
      'trace',
      'exception',
    ],
    safePair: null,
    mcpTools: ['digma', 'context7', 'github', 'filesystem'],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'luma',
    name: 'Luma',
    role: 'specialist',
    domain: 'documentation',
    team: 'coding',
    domainKeywords: [
      'docs',
      'readme',
      'changelog',
      'comment',
      'document',
      'jsdoc',
    ],
    safePair: 'kai',
    mcpTools: ['context7', 'github', 'filesystem'],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'felix',
    name: 'Felix',
    role: 'specialist',
    domain: 'security',
    team: 'coding',
    domainKeywords: [
      'security',
      'auth',
      'owasp',
      'vulnerability',
      'cve',
      'injection',
    ],
    safePair: 'vex',
    mcpTools: ['context7', 'github', 'filesystem'],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'vex',
    name: 'Vex',
    role: 'specialist',
    domain: 'security-testing',
    team: 'coding',
    domainKeywords: [
      'xss',
      'csrf',
      'injection',
      'pentest',
      'exploit',
      'attack',
    ],
    safePair: 'felix',
    mcpTools: ['playwright', 'context7', 'github', 'filesystem'],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  // GENERAL TEAM
  {
    id: 'echo',
    name: 'Echo',
    role: 'specialist',
    domain: 'summarization',
    team: 'general',
    domainKeywords: [
      'summarize',
      'summary',
      'condense',
      'shorter',
      'brief',
      'tldr',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'lyra',
    name: 'Lyra',
    role: 'specialist',
    domain: 'content-writing',
    team: 'general',
    domainKeywords: [
      'post',
      'essay',
      'caption',
      'article',
      'draft',
      'write',
      'blog',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'spark',
    name: 'Spark',
    role: 'specialist',
    domain: 'ideation',
    team: 'general',
    domainKeywords: [
      'creative',
      'ideation',
      'brainstorm',
      'ideas',
      'concept',
      'generate ideas',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'zoe',
    name: 'Zoe',
    role: 'specialist',
    domain: 'communication',
    team: 'general',
    domainKeywords: [
      'rewrite',
      'email',
      'reply',
      'communication',
      'message',
      'draft email',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'gist',
    name: 'Gist',
    role: 'specialist',
    domain: 'explanation',
    team: 'general',
    domainKeywords: [
      'explain',
      'analogy',
      'simplify',
      'understand',
      'what is',
      'how does',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'memo',
    name: 'Memo',
    role: 'specialist',
    domain: 'organization',
    team: 'general',
    domainKeywords: [
      'organize',
      'bullet',
      'list',
      'headers',
      'structure',
      'format',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'tran',
    name: 'Tran',
    role: 'specialist',
    domain: 'translation',
    team: 'general',
    domainKeywords: [
      'translate',
      'translation',
      'multilingual',
      'language',
      'french',
      'spanish',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'plan',
    name: 'Plan',
    role: 'specialist',
    domain: 'planning',
    team: 'general',
    domainKeywords: [
      'plan',
      'task',
      'steps',
      'duration',
      'action',
      'roadmap',
      'schedule',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'vibe',
    name: 'Vibe',
    role: 'specialist',
    domain: 'tone',
    team: 'general',
    domainKeywords: [
      'tone',
      'style',
      'formal',
      'casual',
      'rewrite tone',
      'voice',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'quest',
    name: 'Quest',
    role: 'specialist',
    domain: 'qa',
    team: 'general',
    domainKeywords: ['question', 'answer', 'faq', 'qa', 'knowledge', 'tell me'],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  // RESEARCH TEAM
  {
    id: 'lit',
    name: 'Lit',
    role: 'specialist',
    domain: 'literature-review',
    team: 'research',
    domainKeywords: [
      'literature',
      'academic',
      'papers',
      'research',
      'search',
      'survey',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'cite',
    name: 'Cite',
    role: 'specialist',
    domain: 'citation',
    team: 'research',
    domainKeywords: [
      'citation',
      'cite',
      'bibliography',
      'apa',
      'mla',
      'ieee',
      'reference',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'hypo',
    name: 'Hypo',
    role: 'specialist',
    domain: 'hypothesis',
    team: 'research',
    domainKeywords: [
      'hypothesis',
      'experiment',
      'variables',
      'design',
      'test hypothesis',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'peer',
    name: 'Peer',
    role: 'specialist',
    domain: 'peer-review',
    team: 'research',
    domainKeywords: [
      'peer review',
      'critique',
      'methodological',
      'rigor',
      'paper review',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'scribe',
    name: 'Scribe',
    role: 'specialist',
    domain: 'research-writing',
    team: 'research',
    domainKeywords: [
      'draft',
      'whitepaper',
      'specification',
      'report',
      'write up',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'tutor',
    name: 'Tutor',
    role: 'specialist',
    domain: 'teaching',
    team: 'research',
    domainKeywords: [
      'tutor',
      'learn',
      'explain',
      'equations',
      'intuitive',
      'teach',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'low',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'prof',
    name: 'Prof',
    role: 'specialist',
    domain: 'academic-guidance',
    team: 'research',
    domainKeywords: [
      'professor',
      'mentor',
      'guidance',
      'curate',
      'academic advice',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'grant',
    name: 'Grant',
    role: 'specialist',
    domain: 'grant-writing',
    team: 'research',
    domainKeywords: ['grant', 'proposal', 'funding', 'business case', 'impact'],
    safePair: null,
    mcpTools: [],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'data',
    name: 'Data',
    role: 'specialist',
    domain: 'data-analysis',
    team: 'research',
    domainKeywords: [
      'data',
      'dataset',
      'statistics',
      'trends',
      'processing',
      'analysis',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
  {
    id: 'synth',
    name: 'Synth',
    role: 'specialist',
    domain: 'synthesis',
    team: 'research',
    domainKeywords: [
      'synthesize',
      'integrate',
      'consolidate',
      'findings',
      'cross-domain',
    ],
    safePair: null,
    mcpTools: [],
    costTier: 'medium',
    isCustom: false,
    tenantId: null,
  },
];

@Injectable()
export class AgentRegistryService {
  private readonly logger = new Logger(AgentRegistryService.name);

  constructor(
    @InjectRepository(Agent)
    private readonly agentRepo: Repository<Agent>,
  ) {}

  async getRegistry(tenantId: string): Promise<AgentManifest[]> {
    const manifests: AgentManifest[] = [...PLATFORM_SPECIALISTS];

    try {
      const customAgents = await this.agentRepo.find({
        where: { tenantId },
        select: ['id', 'name', 'role', 'domain', 'adapterConfig', 'tenantId'],
      });

      for (const agent of customAgents) {
        const soul = (agent.adapterConfig as any)?.soul ?? {};
        manifests.push({
          id: agent.id,
          name: agent.name,
          role: agent.role,
          domain: agent.domain ?? 'custom',
          team: 'custom',
          domainKeywords: soul.domainKeywords ?? [],
          safePair: soul.safePair ?? null,
          mcpTools: soul.mcpTools ?? [],
          costTier: soul.costTier ?? 'medium',
          isCustom: true,
          tenantId: agent.tenantId,
        });
      }

      this.logger.log(
        `[AgentRegistry] Loaded ${manifests.length} agents for tenant ${tenantId} (${PLATFORM_SPECIALISTS.length} platform, ${customAgents.length} custom)`,
      );
    } catch (err) {
      this.logger.error(
        `[AgentRegistry] Failed to load custom agents for tenant ${tenantId}`,
        (err as Error).stack,
      );
    }

    return manifests;
  }

  async getManifest(
    agentId: string,
    tenantId: string,
  ): Promise<AgentManifest | null> {
    const registry = await this.getRegistry(tenantId);
    return registry.find((m) => m.id === agentId) ?? null;
  }
}
