import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
} from 'typeorm';

@Entity('project_feed_messages')
export class ProjectFeedMessage {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  tenantId: string;

  @Column()
  projectId: string;

  @Column({ type: 'varchar', length: 50 })
  type:
    | 'vision_ready'
    | 'task_complete'
    | 'audit_complete'
    | 'agent_message'
    | 'lifecycle_started'
    | 'lifecycle_updated'
    | 'completion_review'
    | 'project_completed'
    | 'update_requested';

  @Column({ nullable: true })
  specialist: string;

  @Column({ nullable: true })
  outcome: string;

  @Column()
  content: string; // The UI-facing message generated by standard responses

  @Column({ nullable: true })
  refId: string; // The session ID, audit ID, etc.

  @CreateDateColumn()
  createdAt: Date;
}
