export const WORLD_CURRENCIES = [
  {
    code: 'GBP',
    name: 'British Pound',
    symbol: '£',
    countryCode: 'GB',
    exchangeRateToUSD: 0.79,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'USD',
    name: 'US Dollar',
    symbol: '$',
    countryCode: 'US',
    exchangeRateToUSD: 1.0,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    countryCode: 'EU',
    exchangeRateToUSD: 0.92,
    decimalPlaces: 2,
    thousandSeparator: '.',
    decimalSeparator: ',',
  },
  {
    code: 'INR',
    name: 'Indian Rupee',
    symbol: '₹',
    countryCode: 'IN',
    exchangeRateToUSD: 83.5,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    symbol: 'A$',
    countryCode: 'AU',
    exchangeRateToUSD: 1.53,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    symbol: 'C$',
    countryCode: 'CA',
    exchangeRateToUSD: 1.36,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'SGD',
    name: 'Singapore Dollar',
    symbol: 'S$',
    countryCode: 'SG',
    exchangeRateToUSD: 1.34,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'RM',
    countryCode: 'MY',
    exchangeRateToUSD: 4.7,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'ZAR',
    name: 'South African Rand',
    symbol: 'R',
    countryCode: 'ZA',
    exchangeRateToUSD: 18.6,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    countryCode: 'JP',
    exchangeRateToUSD: 149.0,
    decimalPlaces: 0,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
  {
    code: 'AED',
    name: 'UAE Dirham',
    symbol: 'د.إ',
    countryCode: 'AE',
    exchangeRateToUSD: 3.67,
    decimalPlaces: 2,
    thousandSeparator: ',',
    decimalSeparator: '.',
  },
];
