import { TaxType } from '../tax/tax-rate.entity';

export const WORLD_TAX_RATES = [
  {
    code: 'UK_VAT_STD',
    name: 'UK Standard VAT',
    taxType: TaxType.VAT,
    countryCode: 'GB',
    rate: 20.0,
  },
  {
    code: 'UK_VAT_RDC',
    name: 'UK Reduced VAT',
    taxType: TaxType.VAT,
    countryCode: 'GB',
    rate: 5.0,
  },
  {
    code: 'UK_VAT_ZERO',
    name: 'UK Zero Rate VAT',
    taxType: TaxType.VAT,
    countryCode: 'GB',
    rate: 0.0,
  },
  {
    code: 'UK_VAT_EXMT',
    name: 'UK VAT Exempt',
    taxType: TaxType.NONE,
    countryCode: 'GB',
    rate: 0.0,
  },
  {
    code: 'DE_VAT_STD',
    name: 'Germany MwSt Standard',
    taxType: TaxType.VAT,
    countryCode: 'DE',
    rate: 19.0,
  },
  {
    code: 'DE_VAT_RDC',
    name: 'Germany MwSt Reduced',
    taxType: TaxType.VAT,
    countryCode: 'DE',
    rate: 7.0,
  },
  {
    code: 'FR_VAT_STD',
    name: 'France TVA Standard',
    taxType: TaxType.VAT,
    countryCode: 'FR',
    rate: 20.0,
  },
  {
    code: 'FR_VAT_RDC',
    name: 'France TVA Reduced',
    taxType: TaxType.VAT,
    countryCode: 'FR',
    rate: 5.5,
  },
  {
    code: 'IN_GST_0',
    name: 'India GST 0%',
    taxType: TaxType.GST,
    countryCode: 'IN',
    rate: 0.0,
  },
  {
    code: 'IN_GST_5',
    name: 'India GST 5%',
    taxType: TaxType.GST,
    countryCode: 'IN',
    rate: 5.0,
  },
  {
    code: 'IN_GST_12',
    name: 'India GST 12%',
    taxType: TaxType.GST,
    countryCode: 'IN',
    rate: 12.0,
  },
  {
    code: 'IN_GST_18',
    name: 'India GST 18%',
    taxType: TaxType.GST,
    countryCode: 'IN',
    rate: 18.0,
  },
  {
    code: 'IN_GST_28',
    name: 'India GST 28%',
    taxType: TaxType.GST,
    countryCode: 'IN',
    rate: 28.0,
  },
  {
    code: 'AU_GST',
    name: 'Australia GST',
    taxType: TaxType.GST,
    countryCode: 'AU',
    rate: 10.0,
  },
  {
    code: 'CA_GST',
    name: 'Canada Federal GST',
    taxType: TaxType.GST,
    countryCode: 'CA',
    rate: 5.0,
  },
  {
    code: 'CA_HST_ON',
    name: 'Canada HST Ontario',
    taxType: TaxType.HST,
    countryCode: 'CA',
    rate: 13.0,
  },
  {
    code: 'US_NO_TAX',
    name: 'USA No Sales Tax',
    taxType: TaxType.NONE,
    countryCode: 'US',
    rate: 0.0,
  },
  {
    code: 'US_CA_TAX',
    name: 'California Sales Tax',
    taxType: TaxType.SALES_TAX,
    countryCode: 'US',
    rate: 7.25,
  },
  {
    code: 'US_NY_TAX',
    name: 'New York Sales Tax',
    taxType: TaxType.SALES_TAX,
    countryCode: 'US',
    rate: 8.0,
  },
  {
    code: 'SG_GST',
    name: 'Singapore GST',
    taxType: TaxType.GST,
    countryCode: 'SG',
    rate: 9.0,
  },
  {
    code: 'MY_SST',
    name: 'Malaysia SST',
    taxType: TaxType.SST,
    countryCode: 'MY',
    rate: 6.0,
  },
  {
    code: 'ZA_VAT',
    name: 'South Africa VAT',
    taxType: TaxType.VAT,
    countryCode: 'ZA',
    rate: 15.0,
  },
  {
    code: 'JP_CT',
    name: 'Japan Consumption Tax',
    taxType: TaxType.GST,
    countryCode: 'JP',
    rate: 10.0,
  },
  {
    code: 'AE_VAT',
    name: 'UAE VAT',
    taxType: TaxType.VAT,
    countryCode: 'AE',
    rate: 5.0,
  },
];
