import { Repository } from 'typeorm';
import { ItemCategoryTemplate } from '../entities/item-category-template.entity';

/**
 * Comprehensive Category Templates Seed
 *
 * Based on Universal-Menu.json and industry best practices.
 * AI uses these to organize menu items logically.
 */
export async function seedCategoryTemplates(
  repository: Repository<ItemCategoryTemplate>,
): Promise<void> {
  const templates: Partial<ItemCategoryTemplate>[] = [
    // ============ RESTAURANT CATEGORIES ============
    {
      categorySlug: 'appetizers',
      categoryName: 'Appetizers',
      businessType: 'RESTAURANT',
      cuisineType: null,
      isUniversal: true,
      description: 'Start your meal with these delicious bites.',
      icon: '🍤',
      displayOrder: 1,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['popular', 'shareable'],
      suggestedProductCount: { min: 4, max: 8, ideal: 6 },
      typicalProducts: [
        'Wings',
        'Mozzarella Sticks',
        'Nachos',
        'Spring Rolls',
        'Bruschetta',
      ],
      aiGenerationHints: {
        priceRange: { min: 699, max: 1499 },
        portionSize: 'shareable',
        prepComplexity: 'moderate',
        keywords: ['shareable', 'finger food', 'starter'],
        avoidKeywords: ['main course', 'heavy'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'soups-salads',
      categoryName: 'Soups & Salads',
      businessType: 'RESTAURANT',
      cuisineType: null,
      isUniversal: true,
      description: 'Fresh and flavorful soups and salads.',
      icon: '🥗',
      displayOrder: 2,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['healthy', 'fresh'],
      suggestedProductCount: { min: 3, max: 6, ideal: 4 },
      typicalProducts: [
        'Caesar Salad',
        'Garden Salad',
        'Soup of the Day',
        'Greek Salad',
      ],
      aiGenerationHints: {
        priceRange: { min: 799, max: 1599 },
        portionSize: 'medium',
        prepComplexity: 'simple',
        keywords: ['fresh', 'healthy', 'light'],
        avoidKeywords: ['fried', 'heavy'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'pizza',
      categoryName: 'Pizza',
      businessType: 'RESTAURANT',
      cuisineType: 'Italian',
      isUniversal: false,
      description: 'Hand-crafted pizzas made with fresh ingredients.',
      icon: '🍕',
      displayOrder: 3,
      isDefault: false,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['popular', 'customizable'],
      suggestedProductCount: { min: 6, max: 12, ideal: 8 },
      typicalProducts: [
        'Margherita',
        'Pepperoni',
        'Supreme',
        'Hawaiian',
        'Veggie',
        'BBQ Chicken',
      ],
      aiGenerationHints: {
        priceRange: { min: 1099, max: 1999 },
        portionSize: 'large',
        prepComplexity: 'moderate',
        keywords: ['pizza', 'cheese', 'toppings', 'crust'],
        avoidKeywords: ['pasta', 'sandwich'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'main-courses',
      categoryName: 'Main Courses',
      businessType: 'RESTAURANT',
      cuisineType: null,
      isUniversal: true,
      description: 'The heart of our menu, featuring our signature dishes.',
      icon: '🍽️',
      displayOrder: 4,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['popular', 'signature'],
      suggestedProductCount: { min: 8, max: 15, ideal: 10 },
      typicalProducts: ['Steak', 'Chicken', 'Fish', 'Pasta', 'Burger'],
      aiGenerationHints: {
        priceRange: { min: 1499, max: 3999 },
        portionSize: 'large',
        prepComplexity: 'complex',
        keywords: ['main', 'entree', 'signature', 'specialty'],
        avoidKeywords: ['appetizer', 'side', 'dessert'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'sandwiches',
      categoryName: 'Sandwiches & Wraps',
      businessType: 'RESTAURANT',
      cuisineType: null,
      isUniversal: true,
      description: 'Served with your choice of a side.',
      icon: '🥪',
      displayOrder: 3,
      isDefault: false,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['quick', 'customizable'],
      suggestedProductCount: { min: 5, max: 10, ideal: 7 },
      typicalProducts: [
        'Club Sandwich',
        'BLT',
        'Turkey Sub',
        'Chicken Wrap',
        'Veggie Wrap',
      ],
      aiGenerationHints: {
        priceRange: { min: 699, max: 1399 },
        portionSize: 'medium',
        prepComplexity: 'simple',
        keywords: ['sandwich', 'wrap', 'sub', 'bread'],
        avoidKeywords: ['pizza', 'pasta'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'sides',
      categoryName: 'Sides',
      businessType: 'RESTAURANT',
      cuisineType: null,
      isUniversal: true,
      description: 'Perfect accompaniments to any main course.',
      icon: '🍟',
      displayOrder: 5,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['add-on'],
      suggestedProductCount: { min: 4, max: 8, ideal: 5 },
      typicalProducts: [
        'Fries',
        'Onion Rings',
        'Coleslaw',
        'Garlic Bread',
        'Rice',
      ],
      aiGenerationHints: {
        priceRange: { min: 399, max: 899 },
        portionSize: 'small',
        prepComplexity: 'simple',
        keywords: ['side', 'extra', 'accompaniment'],
        avoidKeywords: ['main', 'entree'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'desserts',
      categoryName: 'Desserts',
      businessType: 'RESTAURANT',
      cuisineType: null,
      isUniversal: true,
      description: 'A sweet ending to your meal.',
      icon: '🍰',
      displayOrder: 6,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['sweet', 'indulgent'],
      suggestedProductCount: { min: 3, max: 6, ideal: 4 },
      typicalProducts: ['Cake', 'Ice Cream', 'Brownie', 'Cheesecake', 'Pie'],
      aiGenerationHints: {
        priceRange: { min: 599, max: 1299 },
        portionSize: 'medium',
        prepComplexity: 'moderate',
        keywords: ['sweet', 'dessert', 'cake', 'chocolate'],
        avoidKeywords: ['savory', 'spicy'],
      },
      confidenceScore: 1.0,
    },

    // ============ CAFE CATEGORIES ============
    {
      categorySlug: 'specialty-coffee',
      categoryName: 'Specialty Coffee',
      businessType: 'CAFE',
      cuisineType: null,
      isUniversal: false,
      description:
        'Artisanal espresso and coffee beverages, crafted by our expert baristas.',
      icon: '☕',
      displayOrder: 1,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['popular', 'signature'],
      suggestedProductCount: { min: 6, max: 12, ideal: 8 },
      typicalProducts: [
        'Latte',
        'Cappuccino',
        'Americano',
        'Espresso',
        'Mocha',
        'Macchiato',
      ],
      aiGenerationHints: {
        priceRange: { min: 375, max: 700 },
        portionSize: 'small',
        prepComplexity: 'moderate',
        keywords: ['coffee', 'espresso', 'latte', 'milk'],
        avoidKeywords: ['tea', 'juice', 'food'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'teas',
      categoryName: 'Teas & More',
      businessType: 'CAFE',
      cuisineType: null,
      isUniversal: false,
      description: 'Premium loose-leaf teas and non-coffee specialties.',
      icon: '🍵',
      displayOrder: 2,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['tea', 'healthy'],
      suggestedProductCount: { min: 4, max: 8, ideal: 5 },
      typicalProducts: [
        'Matcha Latte',
        'Chai Latte',
        'Green Tea',
        'Herbal Tea',
        'Hot Chocolate',
      ],
      aiGenerationHints: {
        priceRange: { min: 400, max: 700 },
        portionSize: 'small',
        prepComplexity: 'simple',
        keywords: ['tea', 'matcha', 'chai', 'herbal'],
        avoidKeywords: ['coffee', 'espresso'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'bakery',
      categoryName: 'Bakery',
      businessType: 'CAFE',
      cuisineType: null,
      isUniversal: false,
      description: 'Freshly baked pastries and treats.',
      icon: '🥐',
      displayOrder: 3,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['fresh', 'baked'],
      suggestedProductCount: { min: 5, max: 10, ideal: 7 },
      typicalProducts: [
        'Croissant',
        'Muffin',
        'Scone',
        'Danish',
        'Bagel',
        'Cookie',
      ],
      aiGenerationHints: {
        priceRange: { min: 299, max: 599 },
        portionSize: 'small',
        prepComplexity: 'simple',
        keywords: ['bakery', 'pastry', 'baked', 'fresh'],
        avoidKeywords: ['drink', 'beverage'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'brunch',
      categoryName: 'All-Day Brunch',
      businessType: 'CAFE',
      cuisineType: null,
      isUniversal: false,
      description:
        'Breakfast and lunch favorites, served whenever you want them.',
      icon: '🥑',
      displayOrder: 4,
      isDefault: false,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['breakfast', 'lunch', 'all-day'],
      suggestedProductCount: { min: 5, max: 10, ideal: 7 },
      typicalProducts: [
        'Avocado Toast',
        'Breakfast Burrito',
        'Eggs Benedict',
        'Pancakes',
        'Grain Bowl',
      ],
      aiGenerationHints: {
        priceRange: { min: 899, max: 1699 },
        portionSize: 'medium',
        prepComplexity: 'moderate',
        keywords: ['breakfast', 'brunch', 'eggs', 'toast'],
        avoidKeywords: ['dinner', 'heavy'],
      },
      confidenceScore: 1.0,
    },

    // ============ BAR CATEGORIES ============
    {
      categorySlug: 'signature-cocktails',
      categoryName: 'Signature Cocktails',
      businessType: 'BAR',
      cuisineType: null,
      isUniversal: false,
      description: 'Unique creations from our award-winning mixologists.',
      icon: '🍸',
      displayOrder: 1,
      isDefault: true,
      requiresAgeVerification: true,
      isTimeRestricted: false,
      tags: ['alcohol', 'signature', 'craft'],
      suggestedProductCount: { min: 5, max: 10, ideal: 7 },
      typicalProducts: [
        'Signature Martini',
        'Craft Margarita',
        'House Special',
        'Seasonal Cocktail',
      ],
      aiGenerationHints: {
        priceRange: { min: 1200, max: 2000 },
        portionSize: 'medium',
        prepComplexity: 'complex',
        keywords: ['cocktail', 'signature', 'craft', 'mixology'],
        avoidKeywords: ['beer', 'wine', 'non-alcoholic'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'classic-cocktails',
      categoryName: 'Classic Cocktails',
      businessType: 'BAR',
      cuisineType: null,
      isUniversal: false,
      description: 'Timeless cocktails, executed to perfection.',
      icon: '🥃',
      displayOrder: 2,
      isDefault: true,
      requiresAgeVerification: true,
      isTimeRestricted: false,
      tags: ['alcohol', 'classic'],
      suggestedProductCount: { min: 6, max: 12, ideal: 8 },
      typicalProducts: [
        'Mojito',
        'Old Fashioned',
        'Negroni',
        'Manhattan',
        'Martini',
        'Margarita',
      ],
      aiGenerationHints: {
        priceRange: { min: 1000, max: 1800 },
        portionSize: 'medium',
        prepComplexity: 'moderate',
        keywords: ['classic', 'cocktail', 'traditional'],
        avoidKeywords: ['mocktail', 'non-alcoholic'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'mocktails',
      categoryName: 'Mocktails',
      businessType: 'BAR',
      cuisineType: null,
      isUniversal: false,
      description: 'All the flavor, none of the alcohol. Halal-friendly.',
      icon: '🍹',
      displayOrder: 3,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['non-alcoholic', 'halal', 'family-friendly'],
      suggestedProductCount: { min: 4, max: 8, ideal: 5 },
      typicalProducts: [
        'Virgin Mojito',
        'Shirley Temple',
        'Virgin Piña Colada',
        'Fruit Punch',
      ],
      aiGenerationHints: {
        priceRange: { min: 600, max: 1200 },
        portionSize: 'medium',
        prepComplexity: 'simple',
        keywords: ['mocktail', 'non-alcoholic', 'virgin', 'halal'],
        avoidKeywords: ['alcohol', 'spirit'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'bar-bites',
      categoryName: 'Bar Bites',
      businessType: 'BAR',
      cuisineType: null,
      isUniversal: false,
      description: 'Elevated snacks to complement your drinks.',
      icon: '🍔',
      displayOrder: 4,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['food', 'shareable', 'snacks'],
      suggestedProductCount: { min: 5, max: 10, ideal: 7 },
      typicalProducts: [
        'Truffle Fries',
        'Sliders',
        'Wings',
        'Nachos',
        'Charcuterie Board',
      ],
      aiGenerationHints: {
        priceRange: { min: 899, max: 2499 },
        portionSize: 'shareable',
        prepComplexity: 'moderate',
        keywords: ['shareable', 'snack', 'appetizer', 'finger food'],
        avoidKeywords: ['main course', 'dessert'],
      },
      confidenceScore: 1.0,
    },

    // ============ UNIVERSAL CATEGORIES ============
    {
      categorySlug: 'beverages',
      categoryName: 'Beverages',
      businessType: 'UNIVERSAL',
      cuisineType: null,
      isUniversal: true,
      description: 'Quench your thirst with our selection of drinks.',
      icon: '🥤',
      displayOrder: 7,
      isDefault: true,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['drinks', 'refreshing'],
      suggestedProductCount: { min: 4, max: 10, ideal: 6 },
      typicalProducts: ['Soda', 'Juice', 'Water', 'Iced Tea', 'Lemonade'],
      aiGenerationHints: {
        priceRange: { min: 199, max: 599 },
        portionSize: 'small',
        prepComplexity: 'simple',
        keywords: ['drink', 'beverage', 'refreshing'],
        avoidKeywords: ['food', 'solid'],
      },
      confidenceScore: 1.0,
    },
    {
      categorySlug: 'kids-menu',
      categoryName: 'Kids Menu',
      businessType: 'UNIVERSAL',
      cuisineType: null,
      isUniversal: true,
      description: 'For our guests 12 and under.',
      icon: '🧒',
      displayOrder: 8,
      isDefault: false,
      requiresAgeVerification: false,
      isTimeRestricted: false,
      tags: ['kids', 'family-friendly'],
      suggestedProductCount: { min: 4, max: 8, ideal: 5 },
      typicalProducts: [
        'Chicken Tenders',
        'Mac & Cheese',
        'Mini Burger',
        'Grilled Cheese',
        'Pizza Slice',
      ],
      aiGenerationHints: {
        priceRange: { min: 499, max: 999 },
        portionSize: 'small',
        prepComplexity: 'simple',
        keywords: ['kids', 'simple', 'mild', 'familiar'],
        avoidKeywords: ['spicy', 'complex', 'alcohol'],
      },
      confidenceScore: 1.0,
    },
  ];

  for (const template of templates) {
    const exists = await repository.findOne({
      where: {
        categorySlug: template.categorySlug,
        businessType: template.businessType,
      },
    });

    if (!exists) {
      await repository.save(repository.create(template));
      console.log(
        `✅ Seeded category template: ${template.categorySlug} (${template.businessType})`,
      );
    } else {
      console.log(
        `⏭️  Skipped (exists): ${template.categorySlug} (${template.businessType})`,
      );
    }
  }

  console.log('🎉 Category templates seeding completed!');
}
