import { Repository } from 'typeorm';
import { ModifierTemplate } from '../entities/modifier-template.entity';

/**
 * Comprehensive Modifier Templates Seed
 *
 * Based on Universal-Menu.json and industry best practices.
 * These templates provide AI with reusable modifier blueprints.
 */
export async function seedModifierTemplates(
  repository: Repository<ModifierTemplate>,
): Promise<void> {
  const templates: Partial<ModifierTemplate>[] = [
    // ============ PIZZA MODIFIERS ============
    {
      modifierSlug: 'mod_pizza_size',
      modifierName: 'Pizza Size',
      businessType: 'RESTAURANT',
      categorySlug: 'pizza',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: true,
      minSelections: 1,
      maxSelections: 1,
      displayOrder: 1,
      options: [
        { name: 'Small (10")', priceModifier: 0, isDefault: false },
        { name: 'Medium (12")', priceModifier: 300, isDefault: true },
        { name: 'Large (14")', priceModifier: 500, isDefault: false },
        { name: 'Extra Large (16")', priceModifier: 700, isDefault: false },
      ],
      icon: '📏',
      tags: ['size', 'required', 'pizza'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_pizza_crust',
      modifierName: 'Crust Style',
      businessType: 'RESTAURANT',
      categorySlug: 'pizza',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: true,
      minSelections: 1,
      maxSelections: 1,
      displayOrder: 2,
      options: [
        {
          name: 'Hand Tossed',
          priceModifier: 0,
          dietaryStatus: 'halal',
          isDefault: true,
        },
        {
          name: 'Thin & Crispy',
          priceModifier: 0,
          dietaryStatus: 'halal',
        },
        {
          name: 'Gluten-Free',
          priceModifier: 300,
          dietaryStatus: 'halal',
          allergens: [],
        },
        {
          name: 'Stuffed Crust',
          priceModifier: 250,
          dietaryStatus: 'vegetarian',
          allergens: ['dairy'],
        },
      ],
      icon: '🍕',
      tags: ['crust', 'required', 'pizza'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_pizza_meat_toppings',
      modifierName: 'Meat Toppings',
      businessType: 'RESTAURANT',
      categorySlug: 'pizza',
      isUniversal: false,
      modifierType: 'multi_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: null,
      displayOrder: 3,
      options: [
        {
          name: 'Beef Pepperoni',
          priceModifier: 200,
          dietaryStatus: 'halal',
        },
        {
          name: 'Pork Pepperoni',
          priceModifier: 150,
          dietaryStatus: 'non_halal',
          containsPork: true,
        },
        {
          name: 'Italian Beef Sausage',
          priceModifier: 200,
          dietaryStatus: 'halal',
        },
        {
          name: 'Pork Sausage',
          priceModifier: 150,
          dietaryStatus: 'non_halal',
          containsPork: true,
        },
        {
          name: 'Grilled Chicken',
          priceModifier: 250,
          dietaryStatus: 'halal',
        },
        {
          name: 'Turkey Bacon',
          priceModifier: 200,
          dietaryStatus: 'halal',
        },
        {
          name: 'Pork Bacon',
          priceModifier: 150,
          dietaryStatus: 'non_halal',
          containsPork: true,
        },
        {
          name: 'Ground Beef',
          priceModifier: 200,
          dietaryStatus: 'halal',
        },
        {
          name: 'Ham',
          priceModifier: 150,
          dietaryStatus: 'non_halal',
          containsPork: true,
        },
      ],
      dietaryReplacements: [
        {
          trigger: 'halal',
          originalOption: 'Pork Pepperoni',
          replacementOption: 'Beef Pepperoni',
          autoApply: true,
        },
        {
          trigger: 'halal',
          originalOption: 'Pork Sausage',
          replacementOption: 'Italian Beef Sausage',
          autoApply: true,
        },
        {
          trigger: 'halal',
          originalOption: 'Pork Bacon',
          replacementOption: 'Turkey Bacon',
          autoApply: true,
        },
      ],
      icon: '🥓',
      tags: ['toppings', 'meat', 'customization'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_pizza_veggie_toppings',
      modifierName: 'Vegetable Toppings',
      businessType: 'RESTAURANT',
      categorySlug: 'pizza',
      isUniversal: false,
      modifierType: 'multi_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: null,
      displayOrder: 4,
      options: [
        { name: 'Mushrooms', priceModifier: 100, dietaryStatus: 'vegan' },
        { name: 'Black Olives', priceModifier: 100, dietaryStatus: 'vegan' },
        { name: 'Green Peppers', priceModifier: 100, dietaryStatus: 'vegan' },
        { name: 'Red Onions', priceModifier: 100, dietaryStatus: 'vegan' },
        { name: 'Fresh Tomatoes', priceModifier: 100, dietaryStatus: 'vegan' },
        { name: 'Spinach', priceModifier: 100, dietaryStatus: 'vegan' },
        { name: 'Jalapeños', priceModifier: 100, dietaryStatus: 'vegan' },
        { name: 'Pineapple', priceModifier: 100, dietaryStatus: 'vegan' },
        { name: 'Roasted Garlic', priceModifier: 100, dietaryStatus: 'vegan' },
        {
          name: 'Sun-Dried Tomatoes',
          priceModifier: 150,
          dietaryStatus: 'vegan',
        },
      ],
      icon: '🥬',
      tags: ['toppings', 'vegetable', 'vegan', 'customization'],
      confidenceScore: 1.0,
    },

    // ============ COFFEE / CAFE MODIFIERS ============
    {
      modifierSlug: 'mod_coffee_size',
      modifierName: 'Size',
      businessType: 'CAFE',
      categorySlug: 'coffee',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: true,
      minSelections: 1,
      maxSelections: 1,
      displayOrder: 1,
      options: [
        {
          name: '12oz (Small)',
          priceModifier: 0,
          isDefault: false,
          calories: 150,
        },
        {
          name: '16oz (Medium)',
          priceModifier: 75,
          isDefault: true,
          calories: 200,
        },
        {
          name: '20oz (Large)',
          priceModifier: 150,
          isDefault: false,
          calories: 280,
        },
      ],
      icon: '☕',
      tags: ['size', 'required', 'coffee'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_milk_choice',
      modifierName: 'Milk Choice',
      businessType: 'CAFE',
      categorySlug: 'coffee',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: 1,
      displayOrder: 2,
      options: [
        {
          name: 'Whole Milk',
          priceModifier: 0,
          dietaryStatus: 'vegetarian',
          allergens: ['dairy'],
          isDefault: true,
        },
        {
          name: 'Skim Milk',
          priceModifier: 0,
          dietaryStatus: 'vegetarian',
          allergens: ['dairy'],
        },
        {
          name: 'Oat Milk',
          priceModifier: 75,
          dietaryStatus: 'vegan',
          allergens: [],
        },
        {
          name: 'Almond Milk',
          priceModifier: 75,
          dietaryStatus: 'vegan',
          allergens: ['nuts'],
        },
        {
          name: 'Soy Milk',
          priceModifier: 75,
          dietaryStatus: 'vegan',
          allergens: ['soy'],
        },
        {
          name: 'Coconut Milk',
          priceModifier: 75,
          dietaryStatus: 'vegan',
          allergens: [],
        },
      ],
      icon: '🥛',
      tags: ['milk', 'dietary', 'customization'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_espresso_shots',
      modifierName: 'Espresso Shots',
      businessType: 'CAFE',
      categorySlug: 'coffee',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: 1,
      displayOrder: 3,
      options: [
        { name: 'Single Shot', priceModifier: 0, isDefault: true },
        { name: 'Double Shot', priceModifier: 100, isDefault: false },
        { name: 'Triple Shot', priceModifier: 200, isDefault: false },
        { name: 'Decaf', priceModifier: 0, isDefault: false },
      ],
      icon: '☕',
      tags: ['espresso', 'customization', 'coffee'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_flavor_syrups',
      modifierName: 'Flavor Syrup',
      businessType: 'CAFE',
      categorySlug: 'coffee',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: 1,
      displayOrder: 4,
      options: [
        { name: 'No Flavor', priceModifier: 0, isDefault: true },
        { name: 'Vanilla', priceModifier: 80, isDefault: false },
        { name: 'Caramel', priceModifier: 80, isDefault: false },
        { name: 'Hazelnut', priceModifier: 80, isDefault: false },
        { name: 'Mocha', priceModifier: 80, isDefault: false },
        { name: 'Pumpkin Spice', priceModifier: 100, isDefault: false },
        { name: 'Peppermint', priceModifier: 80, isDefault: false },
      ],
      icon: '🍯',
      tags: ['flavor', 'syrup', 'customization'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_sweetness_level',
      modifierName: 'Sweetness',
      businessType: 'CAFE',
      categorySlug: 'coffee',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: 1,
      displayOrder: 5,
      options: [
        { name: 'Unsweetened', priceModifier: 0 },
        { name: 'Half Sweet', priceModifier: 0 },
        { name: 'Regular Sweet', priceModifier: 0, isDefault: true },
        { name: 'Extra Sweet', priceModifier: 0 },
      ],
      icon: '🍬',
      tags: ['sweetness', 'customization'],
      confidenceScore: 1.0,
    },

    // ============ SANDWICH / SUB MODIFIERS ============
    {
      modifierSlug: 'mod_sandwich_size',
      modifierName: 'Size',
      businessType: 'RESTAURANT',
      categorySlug: 'sandwich',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: true,
      minSelections: 1,
      maxSelections: 1,
      displayOrder: 1,
      options: [
        { name: '6 inch', priceModifier: 0, isDefault: false },
        { name: '12 inch', priceModifier: 400, isDefault: true },
      ],
      icon: '📏',
      tags: ['size', 'required', 'sandwich'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_sandwich_bread',
      modifierName: 'Bread Choice',
      businessType: 'RESTAURANT',
      categorySlug: 'sandwich',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: true,
      minSelections: 1,
      maxSelections: 1,
      displayOrder: 2,
      options: [
        { name: 'White', priceModifier: 0, isDefault: true },
        { name: 'Wheat', priceModifier: 0 },
        { name: 'Sourdough', priceModifier: 50 },
        { name: 'Ciabatta', priceModifier: 75 },
        { name: 'Gluten-Free', priceModifier: 200, allergens: [] },
      ],
      icon: '🍞',
      tags: ['bread', 'required', 'sandwich'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_sandwich_protein',
      modifierName: 'Protein Choice',
      businessType: 'RESTAURANT',
      categorySlug: 'sandwich',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: true,
      minSelections: 1,
      maxSelections: 1,
      displayOrder: 3,
      options: [
        {
          name: 'Turkey Breast',
          priceModifier: 0,
          dietaryStatus: 'halal',
          isDefault: true,
        },
        {
          name: 'Black Forest Ham',
          priceModifier: 0,
          dietaryStatus: 'non_halal',
          containsPork: true,
        },
        { name: 'Roast Beef', priceModifier: 100, dietaryStatus: 'halal' },
        {
          name: 'Salami',
          priceModifier: 50,
          dietaryStatus: 'non_halal',
          containsPork: true,
        },
        { name: 'Grilled Chicken', priceModifier: 150, dietaryStatus: 'halal' },
        { name: 'Tuna Salad', priceModifier: 50, dietaryStatus: 'halal' },
        { name: 'Veggie Patty', priceModifier: 0, dietaryStatus: 'vegetarian' },
      ],
      dietaryReplacements: [
        {
          trigger: 'halal',
          originalOption: 'Black Forest Ham',
          replacementOption: 'Turkey Breast',
          autoApply: true,
        },
        {
          trigger: 'halal',
          originalOption: 'Salami',
          replacementOption: 'Roast Beef',
          autoApply: true,
        },
      ],
      icon: '🥩',
      tags: ['protein', 'required', 'sandwich'],
      confidenceScore: 1.0,
    },

    // ============ BAR / COCKTAIL MODIFIERS ============
    {
      modifierSlug: 'mod_spirit_choice_whiskey',
      modifierName: 'Whiskey Choice',
      businessType: 'BAR',
      categorySlug: 'cocktails',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: 1,
      displayOrder: 1,
      options: [
        {
          name: 'House Bourbon',
          priceModifier: 0,
          isDefault: true,
          containsAlcohol: true,
        },
        { name: "Maker's Mark", priceModifier: 200, containsAlcohol: true },
        { name: 'Woodford Reserve', priceModifier: 400, containsAlcohol: true },
        { name: 'Bulleit Rye', priceModifier: 300, containsAlcohol: true },
      ],
      icon: '🥃',
      tags: ['spirit', 'alcohol', 'premium'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_mocktail_option',
      modifierName: 'Make it a Mocktail',
      businessType: 'BAR',
      categorySlug: 'cocktails',
      isUniversal: false,
      modifierType: 'single_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: 1,
      displayOrder: 2,
      options: [
        {
          name: 'With Alcohol',
          priceModifier: 0,
          isDefault: true,
          containsAlcohol: true,
          dietaryStatus: 'non_halal',
        },
        {
          name: 'Virgin (No Alcohol)',
          priceModifier: -300,
          containsAlcohol: false,
          dietaryStatus: 'halal',
        },
      ],
      icon: '🍹',
      tags: ['mocktail', 'dietary', 'halal'],
      confidenceScore: 1.0,
    },

    // ============ UNIVERSAL MODIFIERS ============
    {
      modifierSlug: 'mod_spice_level',
      modifierName: 'Spice Level',
      businessType: 'UNIVERSAL',
      categorySlug: null,
      isUniversal: true,
      modifierType: 'single_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: 1,
      displayOrder: 10,
      options: [
        { name: 'Mild', priceModifier: 0, isDefault: true },
        { name: 'Medium', priceModifier: 0 },
        { name: 'Hot', priceModifier: 0 },
        { name: 'Extra Hot', priceModifier: 0 },
      ],
      icon: '🌶️',
      tags: ['spice', 'customization', 'universal'],
      confidenceScore: 1.0,
    },
    {
      modifierSlug: 'mod_extra_sauce',
      modifierName: 'Extra Sauce',
      businessType: 'UNIVERSAL',
      categorySlug: null,
      isUniversal: true,
      modifierType: 'multi_select',
      isRequired: false,
      minSelections: 0,
      maxSelections: null,
      displayOrder: 11,
      options: [
        { name: 'Ranch', priceModifier: 50 },
        { name: 'BBQ', priceModifier: 50 },
        { name: 'Garlic Aioli', priceModifier: 75 },
        { name: 'Buffalo', priceModifier: 50 },
        { name: 'Marinara', priceModifier: 50 },
      ],
      icon: '🥫',
      tags: ['sauce', 'customization', 'universal'],
      confidenceScore: 1.0,
    },
  ];

  for (const template of templates) {
    const exists = await repository.findOne({
      where: { modifierSlug: template.modifierSlug },
    });

    if (!exists) {
      await repository.save(repository.create(template));
      console.log(`✅ Seeded modifier template: ${template.modifierSlug}`);
    } else {
      console.log(`⏭️  Skipped (exists): ${template.modifierSlug}`);
    }
  }

  console.log('🎉 Modifier templates seeding completed!');
}
