import { Repository } from 'typeorm';
import { ProductTemplate } from '../entities/product-template.entity';

/**
 * Comprehensive Product Templates Seed
 *
 * Based on Universal-Menu.json, cafes1.json, and industry best practices.
 * AI uses these templates to generate relevant menus for businesses.
 */
export async function seedProductTemplates(
  repository: Repository<ProductTemplate>,
): Promise<void> {
  const templates: Partial<ProductTemplate>[] = [
    // ============ PIZZA PRODUCTS ============
    {
      businessType: 'RESTAURANT',
      cuisineType: 'Italian',
      categorySlug: 'pizza',
      categoryDisplayName: 'Pizza',
      productName: 'Classic Margherita Pizza',
      description:
        'Fresh mozzarella, Roma tomatoes, basil, and our signature marinara sauce on hand-tossed crust.',
      basePrice: 1299,
      suggestedPriceRange: { min: 1099, max: 1699, market: 'mid-range' },
      dietaryStatus: 'vegetarian',
      allergens: ['gluten', 'dairy'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: ['mod_pizza_size', 'mod_pizza_crust'],
      optionalModifiers: ['mod_pizza_veggie_toppings'],
      tags: ['popular', 'vegetarian', 'classic'],
      calories: 2200,
      prepTimeMinutes: 18,
      imagePrompt:
        'A classic margherita pizza with fresh basil leaves, melted mozzarella, and red sauce, wood-fired crust.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'RESTAURANT',
      cuisineType: 'Italian',
      categorySlug: 'pizza',
      categoryDisplayName: 'Pizza',
      productName: 'Halal Pepperoni Feast',
      description:
        '100% Halal beef pepperoni, mozzarella cheese, and marinara sauce. Certified Halal.',
      basePrice: 1399,
      suggestedPriceRange: { min: 1199, max: 1799, market: 'mid-range' },
      dietaryStatus: 'halal',
      allergens: ['gluten', 'dairy'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: ['mod_pizza_size', 'mod_pizza_crust'],
      optionalModifiers: [
        'mod_pizza_meat_toppings',
        'mod_pizza_veggie_toppings',
      ],
      tags: ['popular', 'halal', 'meat'],
      calories: 2600,
      prepTimeMinutes: 18,
      imagePrompt:
        'A delicious pepperoni pizza with generous beef pepperoni slices and melted cheese.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'RESTAURANT',
      cuisineType: 'Italian',
      categorySlug: 'pizza',
      categoryDisplayName: 'Pizza',
      productName: 'Supreme Pizza (Pork)',
      description:
        'Loaded with pork pepperoni, Italian pork sausage, green peppers, onions, mushrooms, and black olives.',
      basePrice: 1599,
      suggestedPriceRange: { min: 1399, max: 1999, market: 'mid-range' },
      dietaryStatus: 'non_halal',
      allergens: ['gluten', 'dairy'],
      containsAlcohol: false,
      containsPork: true,
      isGlutenFree: false,
      requiredModifiers: ['mod_pizza_size', 'mod_pizza_crust'],
      optionalModifiers: [
        'mod_pizza_meat_toppings',
        'mod_pizza_veggie_toppings',
      ],
      tags: ['popular', 'meat', 'loaded'],
      calories: 3200,
      prepTimeMinutes: 20,
      imagePrompt:
        'A loaded supreme pizza with multiple toppings including pepperoni, sausage, and vegetables.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'RESTAURANT',
      cuisineType: 'Italian',
      categorySlug: 'pizza',
      categoryDisplayName: 'Pizza',
      productName: 'Vegan Garden Pizza',
      description:
        'Plant-based cheese, fresh vegetables (mushrooms, spinach, tomatoes, peppers), and vegan pesto drizzle.',
      basePrice: 1449,
      suggestedPriceRange: { min: 1299, max: 1799, market: 'mid-range' },
      dietaryStatus: 'vegan',
      allergens: ['gluten'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: ['mod_pizza_size', 'mod_pizza_crust'],
      optionalModifiers: ['mod_pizza_veggie_toppings'],
      tags: ['vegan', 'healthy', 'vegetarian'],
      calories: 1800,
      prepTimeMinutes: 18,
      imagePrompt:
        'A colorful vegan pizza with plant-based cheese and fresh garden vegetables.',
      confidenceScore: 1.0,
    },

    // ============ COFFEE PRODUCTS ============
    {
      businessType: 'CAFE',
      cuisineType: null,
      categorySlug: 'coffee',
      categoryDisplayName: 'Specialty Coffee',
      productName: 'Classic Latte',
      description:
        'Rich espresso with perfectly steamed milk and a light layer of foam. A timeless favorite.',
      basePrice: 475,
      suggestedPriceRange: { min: 400, max: 600, market: 'mid-range' },
      dietaryStatus: 'vegetarian',
      allergens: ['dairy'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: true,
      sizeOptions: [
        { name: '12oz', priceModifier: 0 },
        { name: '16oz', priceModifier: 75 },
      ],
      requiredModifiers: ['mod_coffee_size'],
      optionalModifiers: [
        'mod_milk_choice',
        'mod_espresso_shots',
        'mod_flavor_syrups',
      ],
      tags: ['popular', 'coffee', 'classic'],
      calories: 190,
      prepTimeMinutes: 4,
      imagePrompt:
        'A latte in a ceramic mug with beautiful latte art on top, seen from a 45-degree angle.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'CAFE',
      cuisineType: null,
      categorySlug: 'coffee',
      categoryDisplayName: 'Specialty Coffee',
      productName: 'Cappuccino',
      description:
        'Equal parts espresso, steamed milk, and rich foam. Bold and velvety.',
      basePrice: 450,
      suggestedPriceRange: { min: 375, max: 575, market: 'mid-range' },
      dietaryStatus: 'vegetarian',
      allergens: ['dairy'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: true,
      sizeOptions: [
        { name: '12oz', priceModifier: 0 },
        { name: '16oz', priceModifier: 75 },
      ],
      requiredModifiers: ['mod_coffee_size'],
      optionalModifiers: ['mod_milk_choice', 'mod_espresso_shots'],
      tags: ['popular', 'coffee', 'classic'],
      calories: 140,
      prepTimeMinutes: 4,
      imagePrompt:
        'A cappuccino with thick foam and cocoa powder dusted on top.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'CAFE',
      cuisineType: null,
      categorySlug: 'coffee',
      categoryDisplayName: 'Specialty Coffee',
      productName: 'Signature Cold Brew',
      description:
        'Steeped for 18 hours for a smooth, rich, and low-acidity coffee experience. Served over ice.',
      basePrice: 515,
      suggestedPriceRange: { min: 450, max: 650, market: 'mid-range' },
      dietaryStatus: 'vegan',
      allergens: [],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: true,
      sizeOptions: [
        { name: '16oz', priceModifier: 0 },
        { name: '20oz', priceModifier: 50 },
      ],
      requiredModifiers: ['mod_coffee_size'],
      optionalModifiers: ['mod_milk_choice', 'mod_flavor_syrups'],
      tags: ['popular', 'cold', 'smooth'],
      calories: 5,
      prepTimeMinutes: 2,
      imagePrompt:
        'A tall glass of dark cold brew coffee with ice, showing condensation on the glass.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'CAFE',
      cuisineType: null,
      categorySlug: 'coffee',
      categoryDisplayName: 'Specialty Coffee',
      productName: 'Caramel Macchiato',
      description:
        'Vanilla-flavored espresso with steamed milk, topped with caramel drizzle.',
      basePrice: 575,
      suggestedPriceRange: { min: 500, max: 700, market: 'mid-range' },
      dietaryStatus: 'vegetarian',
      allergens: ['dairy'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: true,
      sizeOptions: [
        { name: '12oz', priceModifier: 0 },
        { name: '16oz', priceModifier: 75 },
      ],
      requiredModifiers: ['mod_coffee_size'],
      optionalModifiers: ['mod_milk_choice', 'mod_espresso_shots'],
      tags: ['popular', 'sweet', 'signature'],
      calories: 250,
      prepTimeMinutes: 5,
      imagePrompt:
        'A caramel macchiato with visible caramel drizzle on top of white foam.',
      confidenceScore: 1.0,
    },

    // ============ SANDWICH PRODUCTS ============
    {
      businessType: 'RESTAURANT',
      cuisineType: 'American',
      categorySlug: 'sandwich',
      categoryDisplayName: 'Sandwiches & Subs',
      productName: 'Turkey & Swiss Sub',
      description:
        'Sliced turkey breast, Swiss cheese, lettuce, tomato, and mayo on your choice of bread.',
      basePrice: 750,
      suggestedPriceRange: { min: 650, max: 950, market: 'mid-range' },
      dietaryStatus: 'halal',
      allergens: ['gluten', 'dairy', 'eggs'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: ['mod_sandwich_size', 'mod_sandwich_bread'],
      optionalModifiers: [],
      tags: ['popular', 'halal', 'classic'],
      calories: 650,
      prepTimeMinutes: 5,
      imagePrompt:
        'A fresh turkey sub with lettuce and tomato on artisan bread.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'RESTAURANT',
      cuisineType: 'American',
      categorySlug: 'sandwich',
      categoryDisplayName: 'Sandwiches & Subs',
      productName: 'B.L.T (Bacon, Lettuce, Tomato)',
      description:
        'Crispy pork bacon, fresh lettuce, ripe tomatoes, and mayo on toasted bread. Contains pork.',
      basePrice: 699,
      suggestedPriceRange: { min: 599, max: 899, market: 'mid-range' },
      dietaryStatus: 'non_halal',
      allergens: ['gluten', 'eggs'],
      containsAlcohol: false,
      containsPork: true,
      isGlutenFree: false,
      requiredModifiers: ['mod_sandwich_size', 'mod_sandwich_bread'],
      optionalModifiers: [],
      tags: ['classic', 'bacon'],
      calories: 580,
      prepTimeMinutes: 5,
      imagePrompt:
        'A classic BLT sandwich with crispy bacon visible between the bread.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'RESTAURANT',
      cuisineType: 'American',
      categorySlug: 'sandwich',
      categoryDisplayName: 'Sandwiches & Subs',
      productName: 'Veggie Deluxe Sub',
      description:
        'Fresh vegetables, avocado, hummus, and house vinaigrette on whole wheat bread.',
      basePrice: 725,
      suggestedPriceRange: { min: 625, max: 925, market: 'mid-range' },
      dietaryStatus: 'vegan',
      allergens: ['gluten'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: ['mod_sandwich_size', 'mod_sandwich_bread'],
      optionalModifiers: [],
      tags: ['vegan', 'vegetarian', 'healthy'],
      calories: 450,
      prepTimeMinutes: 5,
      imagePrompt: 'A colorful veggie sub with avocado and fresh vegetables.',
      confidenceScore: 1.0,
    },

    // ============ BAR / COCKTAIL PRODUCTS ============
    {
      businessType: 'BAR',
      cuisineType: null,
      categorySlug: 'cocktails',
      categoryDisplayName: 'Signature Cocktails',
      productName: 'Classic Mojito',
      description:
        'White rum, fresh mint, lime juice, sugar, and soda water. Refreshing and timeless.',
      basePrice: 1200,
      suggestedPriceRange: { min: 1000, max: 1500, market: 'mid-range' },
      dietaryStatus: 'non_halal',
      allergens: [],
      containsAlcohol: true,
      containsPork: false,
      isGlutenFree: true,
      requiredModifiers: [],
      optionalModifiers: ['mod_mocktail_option'],
      tags: ['popular', 'refreshing', 'classic'],
      calories: 168,
      prepTimeMinutes: 3,
      imagePrompt:
        'A tall mojito glass with fresh mint, lime, and ice, garnished with a mint sprig.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'BAR',
      cuisineType: null,
      categorySlug: 'cocktails',
      categoryDisplayName: 'Signature Cocktails',
      productName: 'Virgin Mojito (Mocktail)',
      description:
        'All the flavor of a mojito without the alcohol. Fresh mint, lime, sugar, and soda water.',
      basePrice: 800,
      suggestedPriceRange: { min: 650, max: 1000, market: 'mid-range' },
      dietaryStatus: 'halal',
      allergens: [],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: true,
      requiredModifiers: [],
      optionalModifiers: [],
      tags: ['mocktail', 'halal', 'refreshing', 'popular'],
      calories: 120,
      prepTimeMinutes: 3,
      imagePrompt: 'A virgin mojito with fresh mint and lime, no alcohol.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'BAR',
      cuisineType: null,
      categorySlug: 'cocktails',
      categoryDisplayName: 'Classic Cocktails',
      productName: 'Old Fashioned',
      description:
        "Bourbon or rye whiskey, sugar, Angostura bitters, and orange peel. A gentleman's drink.",
      basePrice: 1600,
      suggestedPriceRange: { min: 1400, max: 2000, market: 'premium' },
      dietaryStatus: 'non_halal',
      allergens: [],
      containsAlcohol: true,
      containsPork: false,
      isGlutenFree: true,
      requiredModifiers: [],
      optionalModifiers: ['mod_spirit_choice_whiskey'],
      tags: ['classic', 'sophisticated', 'popular'],
      calories: 180,
      prepTimeMinutes: 4,
      imagePrompt:
        'An Old Fashioned in a crystal rocks glass with a large ice cube and orange peel.',
      confidenceScore: 1.0,
    },

    // ============ APPETIZERS ============
    {
      businessType: 'RESTAURANT',
      cuisineType: 'American',
      categorySlug: 'appetizers',
      categoryDisplayName: 'Appetizers',
      productName: 'Classic Chicken Wings (Halal)',
      description:
        '8 pieces of Halal chicken wings. Choose from Buffalo, BBQ, or Honey Garlic.',
      basePrice: 1099,
      suggestedPriceRange: { min: 899, max: 1399, market: 'mid-range' },
      dietaryStatus: 'halal',
      allergens: [],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: [],
      optionalModifiers: ['mod_spice_level', 'mod_extra_sauce'],
      tags: ['popular', 'halal', 'shareable'],
      calories: 850,
      prepTimeMinutes: 12,
      imagePrompt:
        'A plate of golden-brown chicken wings with sauce on the side.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'RESTAURANT',
      cuisineType: 'American',
      categorySlug: 'appetizers',
      categoryDisplayName: 'Appetizers',
      productName: 'Mozzarella Sticks',
      description:
        '6 pieces of breaded mozzarella cheese, fried golden and served with marinara sauce.',
      basePrice: 899,
      suggestedPriceRange: { min: 699, max: 1199, market: 'mid-range' },
      dietaryStatus: 'vegetarian',
      allergens: ['gluten', 'dairy'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: [],
      optionalModifiers: [],
      tags: ['popular', 'vegetarian', 'kid-friendly'],
      calories: 720,
      prepTimeMinutes: 8,
      imagePrompt:
        'Golden mozzarella sticks with melted cheese visible, marinara sauce on the side.',
      confidenceScore: 1.0,
    },

    // ============ DESSERTS ============
    {
      businessType: 'RESTAURANT',
      cuisineType: null,
      categorySlug: 'desserts',
      categoryDisplayName: 'Desserts',
      productName: 'Chocolate Lava Cake',
      description:
        'Warm dark chocolate cake with a molten center, served with vanilla ice cream.',
      basePrice: 799,
      suggestedPriceRange: { min: 699, max: 999, market: 'mid-range' },
      dietaryStatus: 'vegetarian',
      allergens: ['gluten', 'dairy', 'eggs'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: [],
      optionalModifiers: [],
      tags: ['popular', 'sweet', 'signature'],
      calories: 550,
      prepTimeMinutes: 6,
      imagePrompt:
        'A chocolate lava cake with molten center oozing out, vanilla ice cream on the side.',
      confidenceScore: 1.0,
    },
    {
      businessType: 'CAFE',
      cuisineType: null,
      categorySlug: 'bakery',
      categoryDisplayName: 'Bakery',
      productName: 'Butter Croissant',
      description: 'Flaky, buttery, and baked fresh throughout the day.',
      basePrice: 425,
      suggestedPriceRange: { min: 350, max: 550, market: 'mid-range' },
      dietaryStatus: 'vegetarian',
      allergens: ['gluten', 'dairy'],
      containsAlcohol: false,
      containsPork: false,
      isGlutenFree: false,
      requiredModifiers: [],
      optionalModifiers: [],
      tags: ['popular', 'breakfast', 'pastry'],
      calories: 310,
      prepTimeMinutes: 1,
      imagePrompt:
        'A golden-brown, perfectly flaky butter croissant on a marble surface.',
      confidenceScore: 1.0,
    },
  ];

  for (const template of templates) {
    const exists = await repository.findOne({
      where: {
        productName: template.productName,
        categorySlug: template.categorySlug,
      },
    });

    if (!exists) {
      await repository.save(repository.create(template));
      console.log(`✅ Seeded product template: ${template.productName}`);
    } else {
      console.log(`⏭️  Skipped (exists): ${template.productName}`);
    }
  }

  console.log('🎉 Product templates seeding completed!');
}
