// Auto-generated by NativeAdapterPromoterService — review before deploying
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import * as fs from 'fs/promises';
import * as path from 'path';
import { ApiFusionBlueprint } from '../entities/api-fusion-blueprint.entity';

@Injectable()
export class NativeAdapterPromoterService {
  private readonly logger = new Logger(NativeAdapterPromoterService.name);

  constructor(
    @InjectRepository(ApiFusionBlueprint)
    private readonly blueprintRepo: Repository<ApiFusionBlueprint>,
  ) {}

  async promote(
    blueprintId: string,
    tenantId: string,
  ): Promise<{ filesWritten: string[] }> {
    const blueprint = await this.blueprintRepo.findOne({
      where: { id: blueprintId, tenantId },
    });
    if (!blueprint) throw new NotFoundException('Blueprint not found');

    const provider = blueprint.provider;
    const adapterDir = path.join(
      process.cwd(),
      'backend',
      'src',
      'api-fusion',
      'adapters',
      provider,
    );

    await fs.mkdir(adapterDir, { recursive: true });

    const serviceContent = this.generateServiceFile(provider, blueprint);
    const dtoContent = this.generateDtoFile(provider, blueprint);

    const servicePath = path.join(adapterDir, `${provider}.service.ts`);
    const dtoPath = path.join(adapterDir, `${provider}.dto.ts`);

    await fs.writeFile(servicePath, serviceContent, 'utf8');
    await fs.writeFile(dtoPath, dtoContent, 'utf8');

    await this.blueprintRepo.update(blueprintId, {
      adapterType: 'native_ts',
      promotedAt: new Date(),
    });

    this.logger.log(`Promoted ${provider} to native_ts adapter: ${adapterDir}`);

    return { filesWritten: [servicePath, dtoPath] };
  }

  private generateServiceFile(
    provider: string,
    blueprint: ApiFusionBlueprint,
  ): string {
    const className = this.toPascalCase(provider);
    const endpointMethods = blueprint.endpoints
      .map((e) => {
        const methodName = this.toCamelCase(
          e.summary ||
            `${e.method.toLowerCase()}_${e.path.replace(/\//g, '_')}`,
        );
        return `  async ${methodName}(tenantId: string, payload?: object) {
    return this.executor.call(tenantId, '${provider}', '${e.method} ${e.path}', payload, 'specialist');
  }`;
      })
      .join('\n\n');

    return `// Auto-generated by NativeAdapterPromoterService — review before deploying
import { Injectable } from '@nestjs/common';
import { ApiFusionExecutorService } from '../../services/api-fusion-executor.service';

@Injectable()
export class ${className}AdapterService {
  constructor(private readonly executor: ApiFusionExecutorService) {}

${endpointMethods}
}
`;
  }

  private generateDtoFile(
    provider: string,
    blueprint: ApiFusionBlueprint,
  ): string {
    const className = this.toPascalCase(provider);
    const dtos = blueprint.endpoints
      .map((e) => {
        const dtoName = `${className}${this.toPascalCase(e.summary || e.method)}Dto`;
        return `export class ${dtoName} {
  // Generated from: ${e.method} ${e.path}
  // Add class-validator decorators as needed
  [key: string]: unknown;
}`;
      })
      .join('\n\n');

    return `// Auto-generated by NativeAdapterPromoterService — review before deploying
${dtos}
`;
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
      .replace(/^./, (c) => c.toUpperCase());
  }

  private toCamelCase(str: string): string {
    const pascal = this.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }
}
