export type ProductStatus = "Publish" | "Inactive" | "Draft";
export type ProductCategory =
  | "Smartphone"
  | "Laptop"
  | "Tablet"
  | "Headphones"
  | "Camera"
  | "Smartwatch"
  | "Speaker"
  | "Monitor";

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  inStock: boolean;
  amount: number;
  qty: number;
  status: ProductStatus;
  image: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "Smartphone",
    inStock: true,
    amount: 999,
    qty: 45,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "2",
    name: "MacBook Air M3",
    brand: "Apple",
    category: "Laptop",
    inStock: true,
    amount: 1299,
    qty: 22,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "3",
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Smartphone",
    inStock: false,
    amount: 1199,
    qty: 0,
    status: "Inactive",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "4",
    name: "iPad Pro 13-inch",
    brand: "Apple",
    category: "Tablet",
    inStock: true,
    amount: 1099,
    qty: 31,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Headphones",
    inStock: true,
    amount: 312,
    qty: 18,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "6",
    name: "Dell XPS 15",
    brand: "Dell",
    category: "Laptop",
    inStock: false,
    amount: 1799,
    qty: 0,
    status: "Inactive",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "7",
    name: "Canon EOS R6",
    brand: "Canon",
    category: "Camera",
    inStock: true,
    amount: 2499,
    qty: 7,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "8",
    name: "Apple Watch Series 9",
    brand: "Apple",
    category: "Smartwatch",
    inStock: true,
    amount: 399,
    qty: 54,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "9",
    name: "Samsung Galaxy Tab S9",
    brand: "Samsung",
    category: "Tablet",
    inStock: false,
    amount: 799,
    qty: 0,
    status: "Draft",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "10",
    name: "Bose SoundLink Max",
    brand: "Bose",
    category: "Speaker",
    inStock: true,
    amount: 449,
    qty: 29,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "11",
    name: "LG UltraWide 34\"",
    brand: "LG",
    category: "Monitor",
    inStock: true,
    amount: 699,
    qty: 11,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "12",
    name: "Pixel 8 Pro",
    brand: "Google",
    category: "Smartphone",
    inStock: false,
    amount: 999,
    qty: 0,
    status: "Inactive",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "13",
    name: "Surface Laptop Studio 2",
    brand: "Microsoft",
    category: "Laptop",
    inStock: true,
    amount: 1999,
    qty: 6,
    status: "Draft",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "14",
    name: "Galaxy Watch 6",
    brand: "Samsung",
    category: "Smartwatch",
    inStock: true,
    amount: 299,
    qty: 37,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "15",
    name: "Sony A7 IV",
    brand: "Sony",
    category: "Camera",
    inStock: true,
    amount: 2499,
    qty: 4,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "16",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "Smartphone",
    inStock: true,
    amount: 799,
    qty: 23,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "17",
    name: "Asus ROG Zephyrus",
    brand: "Asus",
    category: "Laptop",
    inStock: false,
    amount: 1599,
    qty: 0,
    status: "Inactive",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "18",
    name: "Jabra Evolve2 85",
    brand: "Jabra",
    category: "Headphones",
    inStock: true,
    amount: 379,
    qty: 16,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "19",
    name: "Amazon Echo Studio",
    brand: "Amazon",
    category: "Speaker",
    inStock: true,
    amount: 199,
    qty: 42,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "20",
    name: "BenQ 27\" 4K",
    brand: "BenQ",
    category: "Monitor",
    inStock: false,
    amount: 549,
    qty: 0,
    status: "Draft",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "21",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    category: "Smartphone",
    inStock: true,
    amount: 1099,
    qty: 9,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "22",
    name: "HP Spectre x360",
    brand: "HP",
    category: "Laptop",
    inStock: true,
    amount: 1499,
    qty: 14,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "23",
    name: "Nikon Z8",
    brand: "Nikon",
    category: "Camera",
    inStock: false,
    amount: 3999,
    qty: 0,
    status: "Inactive",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "24",
    name: "Marshall Stanmore III",
    brand: "Marshall",
    category: "Speaker",
    inStock: true,
    amount: 349,
    qty: 21,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "25",
    name: "Garmin Fenix 7X",
    brand: "Garmin",
    category: "Smartwatch",
    inStock: true,
    amount: 899,
    qty: 8,
    status: "Publish",
    image: "/placeholder.svg?height=40&width=40",
  },
];
