export interface SpecialistIdentity {
  displayName: string;
  monogram: string;
  colour: string;
  team: 'coding' | 'general' | 'research' | 'system';
  description: string;
}

export const SPECIALIST_IDENTITIES: Record<string, SpecialistIdentity> = {
  rex: {
    displayName: 'Rex',
    monogram: 'RX',
    colour: '#3B82F6',
    team: 'coding',
    description: 'Backend engineer',
  },
  nova: {
    displayName: 'Nova',
    monogram: 'NV',
    colour: '#3B82F6',
    team: 'coding',
    description: 'Frontend engineer',
  },
  kai: {
    displayName: 'Kai',
    monogram: 'KI',
    colour: '#3B82F6',
    team: 'coding',
    description: 'Code reviewer',
  },
  sage: {
    displayName: 'Sage',
    monogram: 'SG',
    colour: '#3B82F6',
    team: 'coding',
    description: 'QA engineer',
  },
  pixel: {
    displayName: 'Pixel',
    monogram: 'PX',
    colour: '#3B82F6',
    team: 'coding',
    description: 'Debugger',
  },
  luma: {
    displayName: 'Luma',
    monogram: 'LM',
    colour: '#3B82F6',
    team: 'coding',
    description: 'Documentation',
  },
  orion: {
    displayName: 'Orion',
    monogram: 'OR',
    colour: '#3B82F6',
    team: 'coding',
    description: 'Architect',
  },
  felix: {
    displayName: 'Felix',
    monogram: 'FX',
    colour: '#3B82F6',
    team: 'coding',
    description: 'Security auditor',
  },
  atlas: {
    displayName: 'Atlas',
    monogram: 'AT',
    colour: '#3B82F6',
    team: 'coding',
    description: 'DevOps',
  },
  vex: {
    displayName: 'Vex',
    monogram: 'VX',
    colour: '#3B82F6',
    team: 'coding',
    description: 'Pentester',
  },
  quest: {
    displayName: 'Quest',
    monogram: 'QU',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  echo: {
    displayName: 'Echo',
    monogram: 'EC',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  lyra: {
    displayName: 'Lyra',
    monogram: 'LY',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  spark: {
    displayName: 'Spark',
    monogram: 'SP',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  zoe: {
    displayName: 'Zoe',
    monogram: 'ZO',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  gist: {
    displayName: 'Gist',
    monogram: 'GI',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  memo: {
    displayName: 'Memo',
    monogram: 'ME',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  tran: {
    displayName: 'Tran',
    monogram: 'TR',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  plan: {
    displayName: 'Plan',
    monogram: 'PL',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  vibe: {
    displayName: 'Vibe',
    monogram: 'VI',
    colour: '#8B5CF6',
    team: 'general',
    description: 'General specialist',
  },
  lit: {
    displayName: 'Lit',
    monogram: 'LT',
    colour: '#10B981',
    team: 'research',
    description: 'Literature researcher',
  },
  cite: {
    displayName: 'Cite',
    monogram: 'CT',
    colour: '#10B981',
    team: 'research',
    description: 'Citation specialist',
  },
  hypo: {
    displayName: 'Hypo',
    monogram: 'HY',
    colour: '#10B981',
    team: 'research',
    description: 'Hypothesis generator',
  },
  peer: {
    displayName: 'Peer',
    monogram: 'PE',
    colour: '#10B981',
    team: 'research',
    description: 'Peer reviewer',
  },
  scribe: {
    displayName: 'Scribe',
    monogram: 'SC',
    colour: '#10B981',
    team: 'research',
    description: 'Research writer',
  },
  tutor: {
    displayName: 'Tutor',
    monogram: 'TU',
    colour: '#10B981',
    team: 'research',
    description: 'Explainer',
  },
  prof: {
    displayName: 'Prof',
    monogram: 'PR',
    colour: '#10B981',
    team: 'research',
    description: 'Domain expert',
  },
  grant: {
    displayName: 'Grant',
    monogram: 'GR',
    colour: '#10B981',
    team: 'research',
    description: 'Grant writer',
  },
  data: {
    displayName: 'Data',
    monogram: 'DA',
    colour: '#10B981',
    team: 'research',
    description: 'Data analyst',
  },
  synth: {
    displayName: 'Synth',
    monogram: 'SY',
    colour: '#10B981',
    team: 'research',
    description: 'Knowledge synthesiser',
  },
  'abigail-ceo': {
    displayName: 'Abigail CEO',
    monogram: 'AB',
    colour: '#F59E0B',
    team: 'system',
    description: 'Executive brain',
  },
  'abigail-mind': {
    displayName: 'AbigailMind',
    monogram: 'AM',
    colour: '#F59E0B',
    team: 'system',
    description: 'Coordinator',
  },
  hermes: {
    displayName: 'Hermes',
    monogram: 'HM',
    colour: '#F97316',
    team: 'system',
    description: 'Behavioural observer',
  },
  soul: {
    displayName: 'Soul',
    monogram: 'SL',
    colour: '#6366F1',
    team: 'system',
    description: 'Nightly evolver',
  },
  coordinator: {
    displayName: 'Coordinator',
    monogram: 'CO',
    colour: '#64748B',
    team: 'system',
    description: 'Autonomous planner',
  },
  'audit-loop': {
    displayName: 'AuditLoop',
    monogram: 'AL',
    colour: '#F43F5E',
    team: 'system',
    description: '8-phase quality loop',
  },
  system: {
    displayName: 'System',
    monogram: 'SY',
    colour: '#64748B',
    team: 'system',
    description: 'System',
  },
};

/** Backwards compat — used by existing ProjectFeedListener */
export const getSpecialistName = (id?: string): string =>
  SPECIALIST_IDENTITIES[id ?? '']?.displayName ?? id ?? 'System';
